export const GET_QUESTIONS_SUCCESS = "GET_QUESTIONS_SUCCESS";

export const GET_QUESTIONS_EASY_REQUEST = "GET_QUESTIONS_EASY_REQUEST";
export const GET_QUESTIONS_MEDIUM_REQUEST = "GET_QUESTIONS_MEDIUM_REQUEST";
export const GET_QUESTIONS_HARD_REQUEST = "GET_QUESTIONS_HARD_REQUEST";
